language: c
env:
  - TOOL_NAME=gon TOOL_VERSION=0.2.2 TOOL_TEST_COMMAND='gon --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add $TOOL_NAME ./
  - asdf list-all $TOOL_NAME
  - asdf plugin-test $TOOL_NAME ./ "$TOOL_TEST_COMMAND" --asdf-tool-version $TOOL_VERSION
os:
  - osx
